# Generated by Django 3.2.8 on 2021-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='placed_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='placed_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='@', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0', max_length=13),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Faild')], default='P', max_length=1),
        ),
    ]
